from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from config_schema import load_app_config


@dataclass(frozen=True)
class InstanceComposeSpec:
    instance_dir_name: str
    user_name: str
    config_path: Path
    interest_profile_path: Path
    output_dir: str


def discover_instance_specs(instances_root: str | Path = "instances") -> list[InstanceComposeSpec]:
    root = Path(instances_root).resolve()
    if not root.exists():
        raise ValueError(f"Instances root does not exist: {root}")

    specs: list[InstanceComposeSpec] = []
    seen_user_names: dict[str, Path] = {}

    for instance_dir in sorted((p for p in root.iterdir() if p.is_dir()), key=lambda p: p.name):
        config_path = instance_dir / "config.json"
        if not config_path.exists():
            continue

        profile_path = instance_dir / "interest_profile.json"
        if not profile_path.exists():
            raise ValueError(f"Missing interest profile for instance '{instance_dir.name}': {profile_path}")

        config = load_app_config(str(config_path))
        user_name = config.user.name
        if user_name in seen_user_names:
            raise ValueError(
                f"Duplicate user.name '{user_name}' in {config_path} and {seen_user_names[user_name]}"
            )

        seen_user_names[user_name] = config_path
        specs.append(
            InstanceComposeSpec(
                instance_dir_name=instance_dir.name,
                user_name=user_name,
                config_path=config_path,
                interest_profile_path=profile_path,
                output_dir=config.output_dir,
            )
        )

    return sorted(specs, key=lambda item: item.user_name)


def generate_compose_text(specs: list[InstanceComposeSpec]) -> str:
    lines = [
        "# This file is generated by scripts/generate_compose_from_instances.py",
        "services:",
    ]

    for spec in specs:
        lines.extend(
            [
                f"  {spec.user_name}:",
                "    image: ${NEWS_MONITOR_IMAGE:-news-monitor:latest}",
                "    build: .",
                f"    container_name: {spec.user_name}",
                "    env_file:",
                "      - .env",
                "    environment:",
                "      CONFIG_PATH: /app/instance/config.json",
                "    volumes:",
                "      - ./output:/app/output",
                f"      - ./instances/{spec.instance_dir_name}:/app/instance:ro",
                "    restart: unless-stopped",
                "",
            ]
        )

    if len(lines) > 2 and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def write_compose_file(output_path: str | Path, text: str) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def resolve_instance_config_path_by_user_name(user_name: str, instances_root: str | Path = "instances") -> Path | None:
    for spec in discover_instance_specs(instances_root):
        if spec.user_name == user_name:
            return spec.config_path
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docker-compose.multi-instance.yml from instances/*/config.json")
    parser.add_argument("--instances-root", default="instances", help="Root directory containing instance folders")
    parser.add_argument(
        "--output",
        default="docker-compose.multi-instance.yml",
        help="Path to the generated docker compose file",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the compose file differs from the generated content",
    )
    args = parser.parse_args(argv)

    specs = discover_instance_specs(args.instances_root)
    text = generate_compose_text(specs)
    output_path = Path(args.output)

    if args.check:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if existing != text:
            print(f"Compose file is out of date: {output_path}")
            return 1
        print(f"Compose file is up to date: {output_path}")
        return 0

    write_compose_file(output_path, text)
    print(f"Generated compose file: {output_path}")
    print(f"Discovered instances: {', '.join(spec.user_name for spec in specs) if specs else '(none)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
